CREATE TABLE system_lock (id integer PRIMARY KEY CHECK(id=1), halted boolean NOT NULL DEFAULT false, halt_reason text);
INSERT INTO system_lock(id) VALUES(1);
CREATE TABLE commands (actor text NOT NULL, namespace text NOT NULL, key text NOT NULL, fingerprint text NOT NULL, response jsonb NOT NULL, PRIMARY KEY(actor,namespace,key));
CREATE TABLE audit_events (sequence bigserial PRIMARY KEY, id uuid UNIQUE NOT NULL, actor text NOT NULL, action text NOT NULL, entity text NOT NULL, payload jsonb NOT NULL, previous_hash text NOT NULL, hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE notifications (id uuid PRIMARY KEY, event_id uuid NOT NULL REFERENCES audit_events(id), summary text NOT NULL, acknowledged_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE owner_challenges (id uuid PRIMARY KEY, actor text NOT NULL, action text NOT NULL, payload_hash text NOT NULL, message text NOT NULL, expires_at timestamptz NOT NULL, consumed_at timestamptz);
CREATE TABLE journals (id uuid PRIMARY KEY, kind text NOT NULL, reference text UNIQUE NOT NULL, metadata jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE entries (id bigserial PRIMARY KEY, journal_id uuid NOT NULL REFERENCES journals(id), account text NOT NULL CHECK(account IN ('W1','W2','PRINCIPAL','PNL','WITHDRAWN','POSITION')), amount bigint NOT NULL);
CREATE INDEX entries_account ON entries(account);
CREATE TABLE allocations (id uuid PRIMARY KEY, profit_base bigint NOT NULL CHECK(profit_base>0), protected_amount bigint NOT NULL CHECK(protected_amount>=0), status text NOT NULL CHECK(status IN ('pending','confirmed')), created_at timestamptz NOT NULL DEFAULT now(), confirmed_at timestamptz);
CREATE TABLE bots (id text PRIMARY KEY, name text NOT NULL, department text NOT NULL, specialty text NOT NULL, method text NOT NULL, novelty_key text UNIQUE NOT NULL, contribution text NOT NULL, state text NOT NULL CHECK(state IN ('school','college','paper','retired')), budget_paise bigint NOT NULL CHECK(budget_paise>=0), mentor_id text REFERENCES bots(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sources (id text PRIMARY KEY, name text NOT NULL, url text NOT NULL, approved boolean NOT NULL DEFAULT false);
CREATE TABLE evidence (id uuid PRIMARY KEY, source_id text NOT NULL REFERENCES sources(id), kind text NOT NULL, content text NOT NULL, content_hash text UNIQUE NOT NULL, published_at timestamptz NOT NULL, received_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL CHECK(status IN ('unverified','verified','rejected')), reviewer text, reviewed_at timestamptz);
CREATE TABLE lessons (id uuid PRIMARY KEY, bot_id text NOT NULL REFERENCES bots(id), content text NOT NULL, evidence_id uuid NOT NULL REFERENCES evidence(id), status text NOT NULL CHECK(status IN ('unverified','verified')), author text NOT NULL, reviewer text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE datasets (id uuid PRIMARY KEY, evidence_id uuid NOT NULL REFERENCES evidence(id), training jsonb NOT NULL, holdout jsonb NOT NULL, digest text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE experiments (id uuid PRIMARY KEY, bot_id text NOT NULL REFERENCES bots(id), dataset_id uuid NOT NULL REFERENCES datasets(id), hypothesis text NOT NULL, candidate jsonb, training_report jsonb, evaluation_report jsonb, state text NOT NULL CHECK(state IN ('queued','evaluating','passed','rejected')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(bot_id,dataset_id));
CREATE TABLE jobs (id uuid PRIMARY KEY, experiment_id uuid NOT NULL REFERENCES experiments(id), kind text NOT NULL CHECK(kind IN ('research','evaluation')), state text NOT NULL CHECK(state IN ('queued','running','completed','failed')), worker text, lease_token uuid, lease_until timestamptz, attempts integer NOT NULL DEFAULT 0, UNIQUE(experiment_id,kind));
CREATE TABLE quotes (symbol text PRIMARY KEY, bid bigint NOT NULL CHECK(bid>0), ask bigint NOT NULL CHECK(ask>=bid), observed_at timestamptz NOT NULL, source_id text NOT NULL REFERENCES sources(id));
CREATE TABLE orders (id uuid PRIMARY KEY, bot_id text NOT NULL REFERENCES bots(id), symbol text NOT NULL, side text NOT NULL CHECK(side IN ('buy','sell')), quantity bigint NOT NULL CHECK(quantity>0), reserved_paise bigint NOT NULL CHECK(reserved_paise>=0), evidence_id uuid NOT NULL REFERENCES evidence(id), status text NOT NULL CHECK(status IN ('reserved','filled','cancelled')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE positions (bot_id text NOT NULL REFERENCES bots(id), symbol text NOT NULL, quantity bigint NOT NULL CHECK(quantity>=0), cost_paise bigint NOT NULL CHECK(cost_paise>=0), PRIMARY KEY(bot_id,symbol));
CREATE TABLE fills (id uuid PRIMARY KEY, order_id uuid UNIQUE NOT NULL REFERENCES orders(id), price_paise bigint NOT NULL, quantity bigint NOT NULL, fee_paise bigint NOT NULL, journal_id uuid NOT NULL REFERENCES journals(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE incidents (id uuid PRIMARY KEY, reporter text NOT NULL, description text NOT NULL, severity text NOT NULL CHECK(severity IN ('warning','critical')), status text NOT NULL CHECK(status IN ('open','resolved')), resolution_evidence uuid REFERENCES evidence(id), created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE evidence ADD COLUMN author text NOT NULL;
CREATE TABLE bot_curriculum (bot_id text NOT NULL REFERENCES bots(id), lesson_id uuid NOT NULL REFERENCES lessons(id), PRIMARY KEY(bot_id,lesson_id));
CREATE FUNCTION reject_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Historical financial and audit records are append-only'; END $$;
CREATE TRIGGER protect_journals BEFORE UPDATE OR DELETE ON journals FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
CREATE TRIGGER protect_entries BEFORE UPDATE OR DELETE ON entries FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
CREATE TRIGGER protect_audit BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
CREATE FUNCTION check_journal_balance() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
  IF (SELECT COALESCE(SUM(amount),0) FROM entries WHERE journal_id=NEW.journal_id) <> 0 THEN RAISE EXCEPTION 'Unbalanced journal'; END IF;
  RETURN NEW;
END $$;
CREATE CONSTRAINT TRIGGER balanced_journal AFTER INSERT ON entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_journal_balance();
